Bootup staking (#6)
* wip for switching to arbitrium network for /play page

* .

* wip for calling switchNetwork() in /play mode

* clean up

* added force refresh upon any network change

* updated GameScreen component to be more modular

* Revert "updated GameScreen component to be more modular"

This reverts commit da457ebe4ed263990c54c014812cbfc09530ca97.

* Revert "Revert "updated GameScreen component to be more modular""

This reverts commit 22895c141c0e3f6261b1cd7bd42e871019cc352e.

* updated multiplayerTest UI and network switching feature

* remove printout

* code cleanup and updated code to using newer ethereum api to fix warnings

* clean up mobile error message and added function isMetaMaskInstalled

* fixed warnings, edited genesis

* added levels for bobots

* Changed MobileMessage to ErrorMessage, added render() for conditional check and isMetaMaskLocked()

* fix render bug when web browser does not have metamask installed

* added error message if metamask is locked

* text update

* wip for switch network button as specified by docs

* Updated network switching to be using button onClick

* clean up

* Updated MultiplayerTest with networking switching

* wip

* unity build

* unlocked build

* [ERROR] change the variables

* commit before change branch

* edited interface contracts

* commit interface contracts

* commit before merge

* staking (not tested)

* minor changes

* add return function

* wip for Stake_Request

* contract wip

* core chamber wip

* wip to test contract's getStakingState(), stakeInCoreChamber and unstakeInCoreChamber

* updated bobotGenesis and installationCoreChamber contract address

* updated bobotGenesis.json and dev build to fix bootup start issue hang

* updated variable namings in ContractAddress.tsx

* updated installationCoreChamber abi json and bobotGenesis address

* stakeGenesis function works but wip for unstakeGenesis function

* wip for calling contract.MintBobot

error: Error: invalid value for array (argument="value", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.0)

* Update BootUpStation.tsx

* updated network check for staking

* updated mintbobot() with network check

* updated BobotGenesis contract and lunar cid for merkle

* updated installationCoreChamber contract address

* added ReceiveTokenStakeStatus_Callback for stake and unstake

* contract address

* Update ContractAddress.tsx

* Update ContractAddress.tsx

* updated blockchain functions to send from react to unity

* updated with latest webgl build

* fix warning

Co-authored-by: Farzaana <farzaanaxd@gmail.com>
Co-authored-by: theonteo <56335249+theonteo@users.noreply.github.com>